### ISSUE TITLE
NetSoakTest stats increase unexpectedly

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de-netsoaktest#19]
[Migrated from JIRA LYN-10262]
When NetSoakTest is run as a non loopback server, receive stats increase despite no actual receives occuring. 
----
*Found in Build*: 2/10/2022

*Reproducibility*: 100%

*Prerequisites*:

*Steps to Reproduce*: Run NetSoakTest in server only mode

*Expected Result*: NetSoakTest stats increase only with relevant traffic.

*Actual Result*: – NetSoakTest stats increase despite no relevant traffic.

**Comment by AMZN-puvvadar** [comment]
As of o3de development branch at [c00b740](https://github.com/o3de/o3de/commit/c00b74013c69ea4717aa935af834520faaa88252) and o3de-netsoaktest at [cddf022](https://github.com/o3de/o3de-netsoaktest/commit/cddf022879f6f527d01577e8a58a2ba030f2faaf) this issue no longer reproduces.

Testing with Host or Client mode on TCP or UDP with or without connection quality configuration produces no unexpected stat increase.
